hostname = www.youtube.com, youtubei.googleapis.com

^https:\/\/www\.youtube\.com\/youtubei\/v1\/(get_watch|next|player|browse|search|reel) url script-response-body https://raw.githubusercontent.com/m6506659306/QuantumultX/refs/heads/main/Rewrite/youtube.player.response.js

^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(get_watch|next|player|browse|search|reel) url script-response-body https://raw.githubusercontent.com/m6506659306/QuantumultX/refs/heads/main/Rewrite/youtube.player.response.js
